const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
   SPARK-X-2025;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUpCanFCY0cwUDNDY1lrbGtoV1l3UkNCN2h1VzRVUzJoMzNITmhJRk5FYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiem05QTF0Si8wYlA4dUhGQUcwVllCL05NTmZMaXhvTmViM2xWMDV0UW54MD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0SExaWXVVMlEraGxzb1VzczNaMitMVEdaL1hST1RubmRHN3VwSWtHRWs0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1WUk2QzNQamZsT05jYzNEWkxTaGtGeXNFWXVNR3F3MXE5Zk5aWCtqUUZjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitIRXFHNXpBM21Ea0ZDV1puNm9MSy9NWXFUYkJpNWFIUnQybGtnMFJTRk09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImpYVTBKdEhCdzV3WFIvUWl1YkxybmN5N3FHVE5LTG5ZUnE0WFhkYk0vMUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUs2N2dHNVQrTHprNDNFWWxYMytHREFrR0FrVEpxNngwSkd5ZGZMZ3FFcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV1liY0pMSGdVQXE0VVd5WG1jckxGcUFZRjhMK2dxODBnUG1lY0k3TDZFYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJ2VkYvM1B1N3ZLZllCWGVndlB2dExORVNMOEJSbUY5WnI3bGl2UGJuQVg1WVg2WkozbEUxRis5WXpyM09pYndQK2IwU2pUUVA2VE1lTUJMM1BDdmlnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjU0LCJhZHZTZWNyZXRLZXkiOiJSSGxWSTBmcThjRDBxNlRRK3RjVktoSUF5aWNHeGpodE10VXVmRm02WVFZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc2ODY2Mjc3N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3MTg5MTExQ0VBODIxNTNBNjI0ODU4QjcwMjEzMTgxMSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQzODQ3MDA0fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3Njg2NjI3NzdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRTFCNjY4ODk4RTU5Mjk1QzU0QkVDQjA3NjdBMkFDOUQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0Mzg0NzAwNH1dLCJuZXh0UHJlS2V5SWQiOjYxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6NjEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiSDRUQVJLOERTNWFOUnB0eUdjRS16QSIsInBob25lSWQiOiI0Mjg0MDI5My05MDBmLTQwNzItOWM5NS00NzEwZjljOTY1ZDkiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaEIwbStlamk0NnJDeFprNjFmdWZScVI2cUxnPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNIRyt6cFhvWHJmamlralcxbno2blFzNTBJND0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJDWFg3VkpISiIsIm1lIjp7ImlkIjoiMjU0NzY4NjYyNzc3OjM4QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkpvaG4gS2lueXVhIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQZlUvTzhCRU12OHc3OEdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ0YjJqaDlSYVh5UDdpUEhiUlNvZndOK3EvVUlRTi9QdUJFT29YNFVGUmlzPSIsImFjY291bnRTaWduYXR1cmUiOiJqV2R4Z1JEdTZ2ZnQrQVVWd2cySDMwME83UXp3MG5PdmprTm1oVnV4RGV6SnJVLytjY0lNRjUxcGY1c1dvQWFJbGh6UHpVL09kck1uS1oxc1NBQjNCUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiM3FGR2ErNXg0Rzg2Mm83MW9SeG9DalVGOGV1ZWppYW9wYndkb2xpa1MxMUNrVzFxM2pmZDl5QnM5L0h1RXB1MVFFQ0FNV0hiUUM1MzUrbkFBYnFBZ3c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3Njg2NjI3Nzc6MzhAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYlc5bzRmVVdsOGorNGp4MjBVcUg4RGZxdjFDRURmejdnUkRxRitGQlVZciJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0Mzg0NzAwMCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFMNFEifQ== : process.env.SESSION_ID || "enter your session",
    CAPTION: process.env.CAPTION || "*ᴘᴏᴡᴅᴇʀᴇᴅ ʙʏ ᴛᴀʟᴋᴅʀᴏᴠᴇ*",
    ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    READ_MESSAGE: process.env.READ_MESSAGE || "false", // Added auto-read configuration
    AUTO_TYPING: process.env.AUTO_TYPING || "true",
    CURRENT_STATUS: process.env.CURRENT_STATUS || "false",
    MODE: process.env.MODE || "public",
    AUTO_VOICE: process.env.AUTO_VOICE || "false",
    AUTO_STICKER: process.env.AUTO_STICKER || "false",
    AUTO_REPLY: process.env.AUTO_REPLY || "false",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://i.imgur.com/UfzyhWN.jpeg",
    ALIVE_MSG: process.env.ALIVE_MSG || "HII DEAR IM ONLINE I'M BYTE-LITE WHATSAPP BOT 😊♻️",
    ANTI_LINK: process.env.ANTI_LINK || "true",
    ANTI_BAD: process.env.ANTI_BAD || "true",
    PREFIX: process.env.PREFIX || ".",
    FAKE_RECORDING: process.env.FAKE_RECORDING || "false",
    AUTO_REACT: process.env.AUTO_REACT || "true",
    HEART_REACT: process.env.HEART_REACT || "false",
    OWNER_REACT: process.env.OWNER_REACT || "false",
    BOT_NAME: process.env.BOT_NAME || "ʙʏᴛᴇ-ʟɪᴛᴇ",
    AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY || "true",
    AUTO_STATUS__MSG: process.env.AUTO_STATUS__MSG || "`𝒚𝒐𝒖𝒓 𝒔𝒕𝒂𝒕𝒖𝒔 𝒔𝒆𝒆𝒏 𝒋𝒖𝒔𝒕 𝒏𝒐𝒘 𝒃𝒚 𝒃𝒚𝒕𝒆-𝒍𝒊𝒕𝒆`",
    OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
